language: java
jdk:
  - openjdk8

script:
  ./gradlew check

env:
  global:
    - CODECOV_TOKEN="dee47087-d32c-4df8-bca6-f7cae78ddf74"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - dda.90@mail.ru
    on_success: never # default: change
    on_failure: always # default: always